// *** WARNING ***
// This file is generated by gendriver.rb
// Keep untouched or ruin the abstraction
#include "drivers.h"
#include "analyzer_driver_impl.h"

analyzer_driver_ref analyzer_driver_plug(core_ref core)
{
    analyzer_driver_ref driver = NULL;

    GUARD(driver = analyzer_driver_create(core));

    cpu_event_attach_listener(&core->events.cpu,
        &(cpu_event_listener_t) {
            .context = driver,
                    .on_decode = (cpu_event_callback_on_decode_t)analyzer_driver_on_cpu_decode,
                .on_step = (cpu_event_callback_on_step_t)analyzer_driver_on_cpu_step,
                .on_read = (cpu_event_callback_on_read_t)analyzer_driver_on_cpu_read,
                .on_write = (cpu_event_callback_on_write_t)analyzer_driver_on_cpu_write,
                .on_interrupt = (cpu_event_callback_on_interrupt_t)analyzer_driver_on_cpu_interrupt,
        });
    core_event_attach_listener(&core->events.core,
        &(core_event_listener_t) {
            .context = driver,
                    .on_start = (core_event_callback_on_start_t)analyzer_driver_on_core_start,
                .on_pause = (core_event_callback_on_pause_t)analyzer_driver_on_core_pause,
                .on_resume = (core_event_callback_on_resume_t)analyzer_driver_on_core_resume,
                .on_poll_in_pause = (core_event_callback_on_poll_in_pause_t)analyzer_driver_on_core_poll_in_pause,
        });
    ppu_event_attach_listener(&core->events.ppu,
        &(ppu_event_listener_t) {
            .context = driver,
                    .on_frame = (ppu_event_callback_on_frame_t)analyzer_driver_on_ppu_frame,
                .on_scanline = (ppu_event_callback_on_scanline_t)analyzer_driver_on_ppu_scanline,
        });

    core_event_attach_listener(&core->events.core, &(core_event_listener_t) {
        .context = driver,
        .on_destroy = (core_event_callback_on_destroy_t)analyzer_driver_destroy,
    });

    return driver;
error:
    analyzer_driver_destroy(driver);
    return NULL;
}

void analyzer_driver_detach_cpu_decode(analyzer_driver_ref self, core_ref core)
{
    cpu_event_emitter_t *emitter = &core->events.cpu;
    cpu_event_detach_listener_on_decode(emitter, self);
}
void analyzer_driver_detach_cpu_step(analyzer_driver_ref self, core_ref core)
{
    cpu_event_emitter_t *emitter = &core->events.cpu;
    cpu_event_detach_listener_on_step(emitter, self);
}
void analyzer_driver_detach_cpu_read(analyzer_driver_ref self, core_ref core)
{
    cpu_event_emitter_t *emitter = &core->events.cpu;
    cpu_event_detach_listener_on_read(emitter, self);
}
void analyzer_driver_detach_cpu_write(analyzer_driver_ref self, core_ref core)
{
    cpu_event_emitter_t *emitter = &core->events.cpu;
    cpu_event_detach_listener_on_write(emitter, self);
}
void analyzer_driver_detach_cpu_interrupt(analyzer_driver_ref self, core_ref core)
{
    cpu_event_emitter_t *emitter = &core->events.cpu;
    cpu_event_detach_listener_on_interrupt(emitter, self);
}
void analyzer_driver_detach_core_start(analyzer_driver_ref self, core_ref core)
{
    core_event_emitter_t *emitter = &core->events.core;
    core_event_detach_listener_on_start(emitter, self);
}
void analyzer_driver_detach_core_pause(analyzer_driver_ref self, core_ref core)
{
    core_event_emitter_t *emitter = &core->events.core;
    core_event_detach_listener_on_pause(emitter, self);
}
void analyzer_driver_detach_core_resume(analyzer_driver_ref self, core_ref core)
{
    core_event_emitter_t *emitter = &core->events.core;
    core_event_detach_listener_on_resume(emitter, self);
}
void analyzer_driver_detach_core_poll_in_pause(analyzer_driver_ref self, core_ref core)
{
    core_event_emitter_t *emitter = &core->events.core;
    core_event_detach_listener_on_poll_in_pause(emitter, self);
}
void analyzer_driver_detach_ppu_frame(analyzer_driver_ref self, core_ref core)
{
    ppu_event_emitter_t *emitter = &core->events.ppu;
    ppu_event_detach_listener_on_frame(emitter, self);
}
void analyzer_driver_detach_ppu_scanline(analyzer_driver_ref self, core_ref core)
{
    ppu_event_emitter_t *emitter = &core->events.ppu;
    ppu_event_detach_listener_on_scanline(emitter, self);
}

void analyzer_driver_unplug(core_ref core, analyzer_driver_ref driver)
{
    analyzer_driver_detach_cpu_decode(driver, core);
    analyzer_driver_detach_cpu_step(driver, core);
    analyzer_driver_detach_cpu_read(driver, core);
    analyzer_driver_detach_cpu_write(driver, core);
    analyzer_driver_detach_cpu_interrupt(driver, core);
    analyzer_driver_detach_core_start(driver, core);
    analyzer_driver_detach_core_pause(driver, core);
    analyzer_driver_detach_core_resume(driver, core);
    analyzer_driver_detach_core_poll_in_pause(driver, core);
    analyzer_driver_detach_ppu_frame(driver, core);
    analyzer_driver_detach_ppu_scanline(driver, core);
    core_event_detach_listener_on_destroy(&core->events.core, driver);

    analyzer_driver_destroy(driver);
}
