// *** WARNING ***
// This file is generated by genevents.rb
// Keep untouched or ruin the abstraction
#pragma once
#include "utils.h"
#include "apu.h"

typedef void (*apu_event_callback_on_sample_t)(void *context, apu_ref apu, uint8_t pulse, uint8_t tnd);
typedef void (*apu_event_callback_on_level30_t)(void *context, apu_ref apu, float level);

typedef struct apu_event_listener {
    void *context;
    // called on generated a sample (pulse and triangle-noise-dmc)
    apu_event_callback_on_sample_t on_sample;
    // emits sum of the level of every 30 samples in floating point (0~30)
    apu_event_callback_on_level30_t on_level30;
} apu_event_listener_t;
