// *** WARNING ***
// This file is generated by gendriver.rb
// Keep untouched or ruin the abstraction
#include "drivers.h"
#include "auto_pause_driver_impl.h"

auto_pause_driver_ref auto_pause_driver_plug(core_ref core, const args_t * args)
{
    auto_pause_driver_ref driver = NULL;

    GUARD(driver = auto_pause_driver_create(core, args));

    cpu_event_attach_listener(&core->events.cpu,
        &(cpu_event_listener_t) {
            .context = driver,
                    .on_step = (cpu_event_callback_on_step_t)auto_pause_driver_on_cpu_step,
        });
    ppu_event_attach_listener(&core->events.ppu,
        &(ppu_event_listener_t) {
            .context = driver,
                    .on_frame = (ppu_event_callback_on_frame_t)auto_pause_driver_on_ppu_frame,
        });
    core_event_attach_listener(&core->events.core,
        &(core_event_listener_t) {
            .context = driver,
                    .on_pause = (core_event_callback_on_pause_t)auto_pause_driver_on_core_pause,
                .on_start = (core_event_callback_on_start_t)auto_pause_driver_on_core_start,
        });

    core_event_attach_listener(&core->events.core, &(core_event_listener_t) {
        .context = driver,
        .on_destroy = (core_event_callback_on_destroy_t)auto_pause_driver_destroy,
    });

    return driver;
error:
    auto_pause_driver_destroy(driver);
    return NULL;
}

void auto_pause_driver_detach_cpu_step(auto_pause_driver_ref self, core_ref core)
{
    cpu_event_emitter_t *emitter = &core->events.cpu;
    cpu_event_detach_listener_on_step(emitter, self);
}
void auto_pause_driver_detach_ppu_frame(auto_pause_driver_ref self, core_ref core)
{
    ppu_event_emitter_t *emitter = &core->events.ppu;
    ppu_event_detach_listener_on_frame(emitter, self);
}
void auto_pause_driver_detach_core_pause(auto_pause_driver_ref self, core_ref core)
{
    core_event_emitter_t *emitter = &core->events.core;
    core_event_detach_listener_on_pause(emitter, self);
}
void auto_pause_driver_detach_core_start(auto_pause_driver_ref self, core_ref core)
{
    core_event_emitter_t *emitter = &core->events.core;
    core_event_detach_listener_on_start(emitter, self);
}

void auto_pause_driver_unplug(core_ref core, auto_pause_driver_ref driver)
{
    auto_pause_driver_detach_cpu_step(driver, core);
    auto_pause_driver_detach_ppu_frame(driver, core);
    auto_pause_driver_detach_core_pause(driver, core);
    auto_pause_driver_detach_core_start(driver, core);
    core_event_detach_listener_on_destroy(&core->events.core, driver);

    auto_pause_driver_destroy(driver);
}
