// *** WARNING ***
// This file is generated by gendriver.rb
// Keep untouched or ruin the abstraction
#pragma once
#include "utils.h"
#include "drivers.h"
#include "core.h"
#include "args.h"

// generated event detacher
void auto_pause_driver_detach_cpu_step(auto_pause_driver_ref self, core_ref core);
void auto_pause_driver_detach_ppu_frame(auto_pause_driver_ref self, core_ref core);
void auto_pause_driver_detach_core_pause(auto_pause_driver_ref self, core_ref core);
void auto_pause_driver_detach_core_start(auto_pause_driver_ref self, core_ref core);

// required implementations
void auto_pause_driver_destroy(auto_pause_driver_ref self);
auto_pause_driver_ref auto_pause_driver_create(core_ref core, const args_t * args);
void auto_pause_driver_on_cpu_step(auto_pause_driver_ref self, cpu_ref cpu);
void auto_pause_driver_on_ppu_frame(auto_pause_driver_ref self, ppu_ref ppu, uint64_t frames);
void auto_pause_driver_on_core_pause(auto_pause_driver_ref self, core_ref core);
void auto_pause_driver_on_core_start(auto_pause_driver_ref self, core_ref core);
