// *** WARNING ***
// This file is generated by gen6502.rb
// Keep untouched or ruin the abstraction
#include "cpu_opcode.h"
#include "utils.h"

op_profile_t op_profiles[256] = {
    [OP_00_BRK] = {
        .op = 0x00,
        .name = {'b','r','k'},
        .official = true,
        .length = 1,
        .mode = OP_MODE_IMPLIED
    },
    [OP_01_ORA] = {
        .op = 0x01,
        .name = {'o','r','a'},
        .official = true,
        .length = 2,
        .mode = OP_MODE_PRE_INDIRECT_X
    },
    [OP_02_STP_UNOFFICIAL] = {
        .op = 0x02,
        .name = {'s','t','p'},
        .official = false,
        .length = 1,
        .mode = OP_MODE_IMPLIED
    },
    [OP_03_SLO_UNOFFICIAL] = {
        .op = 0x03,
        .name = {'s','l','o'},
        .official = false,
        .length = 2,
        .mode = OP_MODE_PRE_INDIRECT_X
    },
    [OP_04_NOP_UNOFFICIAL] = {
        .op = 0x04,
        .name = {'n','o','p'},
        .official = false,
        .length = 2,
        .mode = OP_MODE_ZERO_PAGE
    },
    [OP_05_ORA] = {
        .op = 0x05,
        .name = {'o','r','a'},
        .official = true,
        .length = 2,
        .mode = OP_MODE_ZERO_PAGE
    },
    [OP_06_ASL] = {
        .op = 0x06,
        .name = {'a','s','l'},
        .official = true,
        .length = 2,
        .mode = OP_MODE_ZERO_PAGE
    },
    [OP_07_SLO_UNOFFICIAL] = {
        .op = 0x07,
        .name = {'s','l','o'},
        .official = false,
        .length = 2,
        .mode = OP_MODE_ZERO_PAGE
    },
    [OP_08_PHP] = {
        .op = 0x08,
        .name = {'p','h','p'},
        .official = true,
        .length = 1,
        .mode = OP_MODE_IMPLIED
    },
    [OP_09_ORA] = {
        .op = 0x09,
        .name = {'o','r','a'},
        .official = true,
        .length = 2,
        .mode = OP_MODE_IMMEDIATE
    },
    [OP_0A_ASL] = {
        .op = 0x0A,
        .name = {'a','s','l'},
        .official = true,
        .length = 1,
        .mode = OP_MODE_ACCUMULATOR
    },
    [OP_0B_ANC_UNOFFICIAL] = {
        .op = 0x0B,
        .name = {'a','n','c'},
        .official = false,
        .length = 2,
        .mode = OP_MODE_IMMEDIATE
    },
    [OP_0C_NOP_UNOFFICIAL] = {
        .op = 0x0C,
        .name = {'n','o','p'},
        .official = false,
        .length = 3,
        .mode = OP_MODE_ABSOLUTE
    },
    [OP_0D_ORA] = {
        .op = 0x0D,
        .name = {'o','r','a'},
        .official = true,
        .length = 3,
        .mode = OP_MODE_ABSOLUTE
    },
    [OP_0E_ASL] = {
        .op = 0x0E,
        .name = {'a','s','l'},
        .official = true,
        .length = 3,
        .mode = OP_MODE_ABSOLUTE
    },
    [OP_0F_SLO_UNOFFICIAL] = {
        .op = 0x0F,
        .name = {'s','l','o'},
        .official = false,
        .length = 3,
        .mode = OP_MODE_ABSOLUTE
    },
    [OP_10_BPL] = {
        .op = 0x10,
        .name = {'b','p','l'},
        .official = true,
        .length = 2,
        .mode = OP_MODE_RELATIVE
    },
    [OP_11_ORA] = {
        .op = 0x11,
        .name = {'o','r','a'},
        .official = true,
        .length = 2,
        .mode = OP_MODE_POST_INDIRECT_Y
    },
    [OP_12_STP_UNOFFICIAL] = {
        .op = 0x12,
        .name = {'s','t','p'},
        .official = false,
        .length = 1,
        .mode = OP_MODE_IMPLIED
    },
    [OP_13_SLO_UNOFFICIAL] = {
        .op = 0x13,
        .name = {'s','l','o'},
        .official = false,
        .length = 2,
        .mode = OP_MODE_POST_INDIRECT_Y
    },
    [OP_14_NOP_UNOFFICIAL] = {
        .op = 0x14,
        .name = {'n','o','p'},
        .official = false,
        .length = 2,
        .mode = OP_MODE_ZERO_PAGE_X
    },
    [OP_15_ORA] = {
        .op = 0x15,
        .name = {'o','r','a'},
        .official = true,
        .length = 2,
        .mode = OP_MODE_ZERO_PAGE_X
    },
    [OP_16_ASL] = {
        .op = 0x16,
        .name = {'a','s','l'},
        .official = true,
        .length = 2,
        .mode = OP_MODE_ZERO_PAGE_X
    },
    [OP_17_SLO_UNOFFICIAL] = {
        .op = 0x17,
        .name = {'s','l','o'},
        .official = false,
        .length = 2,
        .mode = OP_MODE_ZERO_PAGE_X
    },
    [OP_18_CLC] = {
        .op = 0x18,
        .name = {'c','l','c'},
        .official = true,
        .length = 1,
        .mode = OP_MODE_IMPLIED
    },
    [OP_19_ORA] = {
        .op = 0x19,
        .name = {'o','r','a'},
        .official = true,
        .length = 3,
        .mode = OP_MODE_ABSOLUTE_Y
    },
    [OP_1A_NOP_UNOFFICIAL] = {
        .op = 0x1A,
        .name = {'n','o','p'},
        .official = false,
        .length = 1,
        .mode = OP_MODE_IMPLIED
    },
    [OP_1B_SLO_UNOFFICIAL] = {
        .op = 0x1B,
        .name = {'s','l','o'},
        .official = false,
        .length = 3,
        .mode = OP_MODE_ABSOLUTE_Y
    },
    [OP_1C_NOP_UNOFFICIAL] = {
        .op = 0x1C,
        .name = {'n','o','p'},
        .official = false,
        .length = 3,
        .mode = OP_MODE_ABSOLUTE_X
    },
    [OP_1D_ORA] = {
        .op = 0x1D,
        .name = {'o','r','a'},
        .official = true,
        .length = 3,
        .mode = OP_MODE_ABSOLUTE_X
    },
    [OP_1E_ASL] = {
        .op = 0x1E,
        .name = {'a','s','l'},
        .official = true,
        .length = 3,
        .mode = OP_MODE_ABSOLUTE_X
    },
    [OP_1F_SLO_UNOFFICIAL] = {
        .op = 0x1F,
        .name = {'s','l','o'},
        .official = false,
        .length = 3,
        .mode = OP_MODE_ABSOLUTE_X
    },
    [OP_20_JSR] = {
        .op = 0x20,
        .name = {'j','s','r'},
        .official = true,
        .length = 3,
        .mode = OP_MODE_ABSOLUTE
    },
    [OP_21_AND] = {
        .op = 0x21,
        .name = {'a','n','d'},
        .official = true,
        .length = 2,
        .mode = OP_MODE_PRE_INDIRECT_X
    },
    [OP_22_STP_UNOFFICIAL] = {
        .op = 0x22,
        .name = {'s','t','p'},
        .official = false,
        .length = 1,
        .mode = OP_MODE_IMPLIED
    },
    [OP_23_RLA_UNOFFICIAL] = {
        .op = 0x23,
        .name = {'r','l','a'},
        .official = false,
        .length = 2,
        .mode = OP_MODE_PRE_INDIRECT_X
    },
    [OP_24_BIT] = {
        .op = 0x24,
        .name = {'b','i','t'},
        .official = true,
        .length = 2,
        .mode = OP_MODE_ZERO_PAGE
    },
    [OP_25_AND] = {
        .op = 0x25,
        .name = {'a','n','d'},
        .official = true,
        .length = 2,
        .mode = OP_MODE_ZERO_PAGE
    },
    [OP_26_ROL] = {
        .op = 0x26,
        .name = {'r','o','l'},
        .official = true,
        .length = 2,
        .mode = OP_MODE_ZERO_PAGE
    },
    [OP_27_RLA_UNOFFICIAL] = {
        .op = 0x27,
        .name = {'r','l','a'},
        .official = false,
        .length = 2,
        .mode = OP_MODE_ZERO_PAGE
    },
    [OP_28_PLP] = {
        .op = 0x28,
        .name = {'p','l','p'},
        .official = true,
        .length = 1,
        .mode = OP_MODE_IMPLIED
    },
    [OP_29_AND] = {
        .op = 0x29,
        .name = {'a','n','d'},
        .official = true,
        .length = 2,
        .mode = OP_MODE_IMMEDIATE
    },
    [OP_2A_ROL] = {
        .op = 0x2A,
        .name = {'r','o','l'},
        .official = true,
        .length = 1,
        .mode = OP_MODE_ACCUMULATOR
    },
    [OP_2B_ANC_UNOFFICIAL] = {
        .op = 0x2B,
        .name = {'a','n','c'},
        .official = false,
        .length = 2,
        .mode = OP_MODE_IMMEDIATE
    },
    [OP_2C_BIT] = {
        .op = 0x2C,
        .name = {'b','i','t'},
        .official = true,
        .length = 3,
        .mode = OP_MODE_ABSOLUTE
    },
    [OP_2D_AND] = {
        .op = 0x2D,
        .name = {'a','n','d'},
        .official = true,
        .length = 3,
        .mode = OP_MODE_ABSOLUTE
    },
    [OP_2E_ROL] = {
        .op = 0x2E,
        .name = {'r','o','l'},
        .official = true,
        .length = 3,
        .mode = OP_MODE_ABSOLUTE
    },
    [OP_2F_RLA_UNOFFICIAL] = {
        .op = 0x2F,
        .name = {'r','l','a'},
        .official = false,
        .length = 3,
        .mode = OP_MODE_ABSOLUTE
    },
    [OP_30_BMI] = {
        .op = 0x30,
        .name = {'b','m','i'},
        .official = true,
        .length = 2,
        .mode = OP_MODE_RELATIVE
    },
    [OP_31_AND] = {
        .op = 0x31,
        .name = {'a','n','d'},
        .official = true,
        .length = 2,
        .mode = OP_MODE_POST_INDIRECT_Y
    },
    [OP_32_STP_UNOFFICIAL] = {
        .op = 0x32,
        .name = {'s','t','p'},
        .official = false,
        .length = 1,
        .mode = OP_MODE_IMPLIED
    },
    [OP_33_RLA_UNOFFICIAL] = {
        .op = 0x33,
        .name = {'r','l','a'},
        .official = false,
        .length = 2,
        .mode = OP_MODE_POST_INDIRECT_Y
    },
    [OP_34_NOP_UNOFFICIAL] = {
        .op = 0x34,
        .name = {'n','o','p'},
        .official = false,
        .length = 2,
        .mode = OP_MODE_ZERO_PAGE_X
    },
    [OP_35_AND] = {
        .op = 0x35,
        .name = {'a','n','d'},
        .official = true,
        .length = 2,
        .mode = OP_MODE_ZERO_PAGE_X
    },
    [OP_36_ROL] = {
        .op = 0x36,
        .name = {'r','o','l'},
        .official = true,
        .length = 2,
        .mode = OP_MODE_ZERO_PAGE_X
    },
    [OP_37_RLA_UNOFFICIAL] = {
        .op = 0x37,
        .name = {'r','l','a'},
        .official = false,
        .length = 2,
        .mode = OP_MODE_ZERO_PAGE_X
    },
    [OP_38_SEC] = {
        .op = 0x38,
        .name = {'s','e','c'},
        .official = true,
        .length = 1,
        .mode = OP_MODE_IMPLIED
    },
    [OP_39_AND] = {
        .op = 0x39,
        .name = {'a','n','d'},
        .official = true,
        .length = 3,
        .mode = OP_MODE_ABSOLUTE_Y
    },
    [OP_3A_NOP_UNOFFICIAL] = {
        .op = 0x3A,
        .name = {'n','o','p'},
        .official = false,
        .length = 1,
        .mode = OP_MODE_IMPLIED
    },
    [OP_3B_RLA_UNOFFICIAL] = {
        .op = 0x3B,
        .name = {'r','l','a'},
        .official = false,
        .length = 3,
        .mode = OP_MODE_ABSOLUTE_Y
    },
    [OP_3C_NOP_UNOFFICIAL] = {
        .op = 0x3C,
        .name = {'n','o','p'},
        .official = false,
        .length = 3,
        .mode = OP_MODE_ABSOLUTE_X
    },
    [OP_3D_AND] = {
        .op = 0x3D,
        .name = {'a','n','d'},
        .official = true,
        .length = 3,
        .mode = OP_MODE_ABSOLUTE_X
    },
    [OP_3E_ROL] = {
        .op = 0x3E,
        .name = {'r','o','l'},
        .official = true,
        .length = 3,
        .mode = OP_MODE_ABSOLUTE_X
    },
    [OP_3F_RLA_UNOFFICIAL] = {
        .op = 0x3F,
        .name = {'r','l','a'},
        .official = false,
        .length = 3,
        .mode = OP_MODE_ABSOLUTE_X
    },
    [OP_40_RTI] = {
        .op = 0x40,
        .name = {'r','t','i'},
        .official = true,
        .length = 1,
        .mode = OP_MODE_IMPLIED
    },
    [OP_41_EOR] = {
        .op = 0x41,
        .name = {'e','o','r'},
        .official = true,
        .length = 2,
        .mode = OP_MODE_PRE_INDIRECT_X
    },
    [OP_42_STP_UNOFFICIAL] = {
        .op = 0x42,
        .name = {'s','t','p'},
        .official = false,
        .length = 1,
        .mode = OP_MODE_IMPLIED
    },
    [OP_43_SRE_UNOFFICIAL] = {
        .op = 0x43,
        .name = {'s','r','e'},
        .official = false,
        .length = 2,
        .mode = OP_MODE_PRE_INDIRECT_X
    },
    [OP_44_NOP_UNOFFICIAL] = {
        .op = 0x44,
        .name = {'n','o','p'},
        .official = false,
        .length = 2,
        .mode = OP_MODE_ZERO_PAGE
    },
    [OP_45_EOR] = {
        .op = 0x45,
        .name = {'e','o','r'},
        .official = true,
        .length = 2,
        .mode = OP_MODE_ZERO_PAGE
    },
    [OP_46_LSR] = {
        .op = 0x46,
        .name = {'l','s','r'},
        .official = true,
        .length = 2,
        .mode = OP_MODE_ZERO_PAGE
    },
    [OP_47_SRE_UNOFFICIAL] = {
        .op = 0x47,
        .name = {'s','r','e'},
        .official = false,
        .length = 2,
        .mode = OP_MODE_ZERO_PAGE
    },
    [OP_48_PHA] = {
        .op = 0x48,
        .name = {'p','h','a'},
        .official = true,
        .length = 1,
        .mode = OP_MODE_IMPLIED
    },
    [OP_49_EOR] = {
        .op = 0x49,
        .name = {'e','o','r'},
        .official = true,
        .length = 2,
        .mode = OP_MODE_IMMEDIATE
    },
    [OP_4A_LSR] = {
        .op = 0x4A,
        .name = {'l','s','r'},
        .official = true,
        .length = 1,
        .mode = OP_MODE_ACCUMULATOR
    },
    [OP_4B_ALR_UNOFFICIAL] = {
        .op = 0x4B,
        .name = {'a','l','r'},
        .official = false,
        .length = 2,
        .mode = OP_MODE_IMMEDIATE
    },
    [OP_4C_JMP] = {
        .op = 0x4C,
        .name = {'j','m','p'},
        .official = true,
        .length = 3,
        .mode = OP_MODE_ABSOLUTE
    },
    [OP_4D_EOR] = {
        .op = 0x4D,
        .name = {'e','o','r'},
        .official = true,
        .length = 3,
        .mode = OP_MODE_ABSOLUTE
    },
    [OP_4E_LSR] = {
        .op = 0x4E,
        .name = {'l','s','r'},
        .official = true,
        .length = 3,
        .mode = OP_MODE_ABSOLUTE
    },
    [OP_4F_SRE_UNOFFICIAL] = {
        .op = 0x4F,
        .name = {'s','r','e'},
        .official = false,
        .length = 3,
        .mode = OP_MODE_ABSOLUTE
    },
    [OP_50_BVC] = {
        .op = 0x50,
        .name = {'b','v','c'},
        .official = true,
        .length = 2,
        .mode = OP_MODE_RELATIVE
    },
    [OP_51_EOR] = {
        .op = 0x51,
        .name = {'e','o','r'},
        .official = true,
        .length = 2,
        .mode = OP_MODE_POST_INDIRECT_Y
    },
    [OP_52_STP_UNOFFICIAL] = {
        .op = 0x52,
        .name = {'s','t','p'},
        .official = false,
        .length = 1,
        .mode = OP_MODE_IMPLIED
    },
    [OP_53_SRE_UNOFFICIAL] = {
        .op = 0x53,
        .name = {'s','r','e'},
        .official = false,
        .length = 2,
        .mode = OP_MODE_POST_INDIRECT_Y
    },
    [OP_54_NOP_UNOFFICIAL] = {
        .op = 0x54,
        .name = {'n','o','p'},
        .official = false,
        .length = 2,
        .mode = OP_MODE_ZERO_PAGE_X
    },
    [OP_55_EOR] = {
        .op = 0x55,
        .name = {'e','o','r'},
        .official = true,
        .length = 2,
        .mode = OP_MODE_ZERO_PAGE_X
    },
    [OP_56_LSR] = {
        .op = 0x56,
        .name = {'l','s','r'},
        .official = true,
        .length = 2,
        .mode = OP_MODE_ZERO_PAGE_X
    },
    [OP_57_SRE_UNOFFICIAL] = {
        .op = 0x57,
        .name = {'s','r','e'},
        .official = false,
        .length = 2,
        .mode = OP_MODE_ZERO_PAGE_X
    },
    [OP_58_CLI] = {
        .op = 0x58,
        .name = {'c','l','i'},
        .official = true,
        .length = 1,
        .mode = OP_MODE_IMPLIED
    },
    [OP_59_EOR] = {
        .op = 0x59,
        .name = {'e','o','r'},
        .official = true,
        .length = 3,
        .mode = OP_MODE_ABSOLUTE_Y
    },
    [OP_5A_NOP_UNOFFICIAL] = {
        .op = 0x5A,
        .name = {'n','o','p'},
        .official = false,
        .length = 1,
        .mode = OP_MODE_IMPLIED
    },
    [OP_5B_SRE_UNOFFICIAL] = {
        .op = 0x5B,
        .name = {'s','r','e'},
        .official = false,
        .length = 3,
        .mode = OP_MODE_ABSOLUTE_Y
    },
    [OP_5C_NOP_UNOFFICIAL] = {
        .op = 0x5C,
        .name = {'n','o','p'},
        .official = false,
        .length = 3,
        .mode = OP_MODE_ABSOLUTE_X
    },
    [OP_5D_EOR] = {
        .op = 0x5D,
        .name = {'e','o','r'},
        .official = true,
        .length = 3,
        .mode = OP_MODE_ABSOLUTE_X
    },
    [OP_5E_LSR] = {
        .op = 0x5E,
        .name = {'l','s','r'},
        .official = true,
        .length = 3,
        .mode = OP_MODE_ABSOLUTE_X
    },
    [OP_5F_SRE_UNOFFICIAL] = {
        .op = 0x5F,
        .name = {'s','r','e'},
        .official = false,
        .length = 3,
        .mode = OP_MODE_ABSOLUTE_X
    },
    [OP_60_RTS] = {
        .op = 0x60,
        .name = {'r','t','s'},
        .official = true,
        .length = 1,
        .mode = OP_MODE_IMPLIED
    },
    [OP_61_ADC] = {
        .op = 0x61,
        .name = {'a','d','c'},
        .official = true,
        .length = 2,
        .mode = OP_MODE_PRE_INDIRECT_X
    },
    [OP_62_STP_UNOFFICIAL] = {
        .op = 0x62,
        .name = {'s','t','p'},
        .official = false,
        .length = 1,
        .mode = OP_MODE_IMPLIED
    },
    [OP_63_RRA_UNOFFICIAL] = {
        .op = 0x63,
        .name = {'r','r','a'},
        .official = false,
        .length = 2,
        .mode = OP_MODE_PRE_INDIRECT_X
    },
    [OP_64_NOP_UNOFFICIAL] = {
        .op = 0x64,
        .name = {'n','o','p'},
        .official = false,
        .length = 2,
        .mode = OP_MODE_ZERO_PAGE
    },
    [OP_65_ADC] = {
        .op = 0x65,
        .name = {'a','d','c'},
        .official = true,
        .length = 2,
        .mode = OP_MODE_ZERO_PAGE
    },
    [OP_66_ROR] = {
        .op = 0x66,
        .name = {'r','o','r'},
        .official = true,
        .length = 2,
        .mode = OP_MODE_ZERO_PAGE
    },
    [OP_67_RRA_UNOFFICIAL] = {
        .op = 0x67,
        .name = {'r','r','a'},
        .official = false,
        .length = 2,
        .mode = OP_MODE_ZERO_PAGE
    },
    [OP_68_PLA] = {
        .op = 0x68,
        .name = {'p','l','a'},
        .official = true,
        .length = 1,
        .mode = OP_MODE_IMPLIED
    },
    [OP_69_ADC] = {
        .op = 0x69,
        .name = {'a','d','c'},
        .official = true,
        .length = 2,
        .mode = OP_MODE_IMMEDIATE
    },
    [OP_6A_ROR] = {
        .op = 0x6A,
        .name = {'r','o','r'},
        .official = true,
        .length = 1,
        .mode = OP_MODE_ACCUMULATOR
    },
    [OP_6B_ARR_UNOFFICIAL] = {
        .op = 0x6B,
        .name = {'a','r','r'},
        .official = false,
        .length = 2,
        .mode = OP_MODE_IMMEDIATE
    },
    [OP_6C_JMP] = {
        .op = 0x6C,
        .name = {'j','m','p'},
        .official = true,
        .length = 3,
        .mode = OP_MODE_INDIRECT
    },
    [OP_6D_ADC] = {
        .op = 0x6D,
        .name = {'a','d','c'},
        .official = true,
        .length = 3,
        .mode = OP_MODE_ABSOLUTE
    },
    [OP_6E_ROR] = {
        .op = 0x6E,
        .name = {'r','o','r'},
        .official = true,
        .length = 3,
        .mode = OP_MODE_ABSOLUTE
    },
    [OP_6F_RRA_UNOFFICIAL] = {
        .op = 0x6F,
        .name = {'r','r','a'},
        .official = false,
        .length = 3,
        .mode = OP_MODE_ABSOLUTE
    },
    [OP_70_BVS] = {
        .op = 0x70,
        .name = {'b','v','s'},
        .official = true,
        .length = 2,
        .mode = OP_MODE_RELATIVE
    },
    [OP_71_ADC] = {
        .op = 0x71,
        .name = {'a','d','c'},
        .official = true,
        .length = 2,
        .mode = OP_MODE_POST_INDIRECT_Y
    },
    [OP_72_STP_UNOFFICIAL] = {
        .op = 0x72,
        .name = {'s','t','p'},
        .official = false,
        .length = 1,
        .mode = OP_MODE_IMPLIED
    },
    [OP_73_RRA_UNOFFICIAL] = {
        .op = 0x73,
        .name = {'r','r','a'},
        .official = false,
        .length = 2,
        .mode = OP_MODE_POST_INDIRECT_Y
    },
    [OP_74_NOP_UNOFFICIAL] = {
        .op = 0x74,
        .name = {'n','o','p'},
        .official = false,
        .length = 2,
        .mode = OP_MODE_ZERO_PAGE_X
    },
    [OP_75_ADC] = {
        .op = 0x75,
        .name = {'a','d','c'},
        .official = true,
        .length = 2,
        .mode = OP_MODE_ZERO_PAGE_X
    },
    [OP_76_ROR] = {
        .op = 0x76,
        .name = {'r','o','r'},
        .official = true,
        .length = 2,
        .mode = OP_MODE_ZERO_PAGE_X
    },
    [OP_77_RRA_UNOFFICIAL] = {
        .op = 0x77,
        .name = {'r','r','a'},
        .official = false,
        .length = 2,
        .mode = OP_MODE_ZERO_PAGE_X
    },
    [OP_78_SEI] = {
        .op = 0x78,
        .name = {'s','e','i'},
        .official = true,
        .length = 1,
        .mode = OP_MODE_IMPLIED
    },
    [OP_79_ADC] = {
        .op = 0x79,
        .name = {'a','d','c'},
        .official = true,
        .length = 3,
        .mode = OP_MODE_ABSOLUTE_Y
    },
    [OP_7A_NOP_UNOFFICIAL] = {
        .op = 0x7A,
        .name = {'n','o','p'},
        .official = false,
        .length = 1,
        .mode = OP_MODE_IMPLIED
    },
    [OP_7B_RRA_UNOFFICIAL] = {
        .op = 0x7B,
        .name = {'r','r','a'},
        .official = false,
        .length = 3,
        .mode = OP_MODE_ABSOLUTE_Y
    },
    [OP_7C_NOP_UNOFFICIAL] = {
        .op = 0x7C,
        .name = {'n','o','p'},
        .official = false,
        .length = 3,
        .mode = OP_MODE_ABSOLUTE_X
    },
    [OP_7D_ADC] = {
        .op = 0x7D,
        .name = {'a','d','c'},
        .official = true,
        .length = 3,
        .mode = OP_MODE_ABSOLUTE_X
    },
    [OP_7E_ROR] = {
        .op = 0x7E,
        .name = {'r','o','r'},
        .official = true,
        .length = 3,
        .mode = OP_MODE_ABSOLUTE_X
    },
    [OP_7F_RRA_UNOFFICIAL] = {
        .op = 0x7F,
        .name = {'r','r','a'},
        .official = false,
        .length = 3,
        .mode = OP_MODE_ABSOLUTE_X
    },
    [OP_80_NOP_UNOFFICIAL] = {
        .op = 0x80,
        .name = {'n','o','p'},
        .official = false,
        .length = 2,
        .mode = OP_MODE_IMMEDIATE
    },
    [OP_81_STA] = {
        .op = 0x81,
        .name = {'s','t','a'},
        .official = true,
        .length = 2,
        .mode = OP_MODE_PRE_INDIRECT_X
    },
    [OP_82_NOP_UNOFFICIAL] = {
        .op = 0x82,
        .name = {'n','o','p'},
        .official = false,
        .length = 2,
        .mode = OP_MODE_IMMEDIATE
    },
    [OP_83_SAX_UNOFFICIAL] = {
        .op = 0x83,
        .name = {'s','a','x'},
        .official = false,
        .length = 2,
        .mode = OP_MODE_PRE_INDIRECT_X
    },
    [OP_84_STY] = {
        .op = 0x84,
        .name = {'s','t','y'},
        .official = true,
        .length = 2,
        .mode = OP_MODE_ZERO_PAGE
    },
    [OP_85_STA] = {
        .op = 0x85,
        .name = {'s','t','a'},
        .official = true,
        .length = 2,
        .mode = OP_MODE_ZERO_PAGE
    },
    [OP_86_STX] = {
        .op = 0x86,
        .name = {'s','t','x'},
        .official = true,
        .length = 2,
        .mode = OP_MODE_ZERO_PAGE
    },
    [OP_87_SAX_UNOFFICIAL] = {
        .op = 0x87,
        .name = {'s','a','x'},
        .official = false,
        .length = 2,
        .mode = OP_MODE_ZERO_PAGE
    },
    [OP_88_DEY] = {
        .op = 0x88,
        .name = {'d','e','y'},
        .official = true,
        .length = 1,
        .mode = OP_MODE_IMPLIED
    },
    [OP_89_NOP_UNOFFICIAL] = {
        .op = 0x89,
        .name = {'n','o','p'},
        .official = false,
        .length = 2,
        .mode = OP_MODE_IMMEDIATE
    },
    [OP_8A_TXA] = {
        .op = 0x8A,
        .name = {'t','x','a'},
        .official = true,
        .length = 1,
        .mode = OP_MODE_IMPLIED
    },
    [OP_8B_XAA_UNOFFICIAL] = {
        .op = 0x8B,
        .name = {'x','a','a'},
        .official = false,
        .length = 2,
        .mode = OP_MODE_IMMEDIATE
    },
    [OP_8C_STY] = {
        .op = 0x8C,
        .name = {'s','t','y'},
        .official = true,
        .length = 3,
        .mode = OP_MODE_ABSOLUTE
    },
    [OP_8D_STA] = {
        .op = 0x8D,
        .name = {'s','t','a'},
        .official = true,
        .length = 3,
        .mode = OP_MODE_ABSOLUTE
    },
    [OP_8E_STX] = {
        .op = 0x8E,
        .name = {'s','t','x'},
        .official = true,
        .length = 3,
        .mode = OP_MODE_ABSOLUTE
    },
    [OP_8F_SAX_UNOFFICIAL] = {
        .op = 0x8F,
        .name = {'s','a','x'},
        .official = false,
        .length = 3,
        .mode = OP_MODE_ABSOLUTE
    },
    [OP_90_BCC] = {
        .op = 0x90,
        .name = {'b','c','c'},
        .official = true,
        .length = 2,
        .mode = OP_MODE_RELATIVE
    },
    [OP_91_STA] = {
        .op = 0x91,
        .name = {'s','t','a'},
        .official = true,
        .length = 2,
        .mode = OP_MODE_POST_INDIRECT_Y
    },
    [OP_92_STP_UNOFFICIAL] = {
        .op = 0x92,
        .name = {'s','t','p'},
        .official = false,
        .length = 1,
        .mode = OP_MODE_IMPLIED
    },
    [OP_93_AHX_UNOFFICIAL] = {
        .op = 0x93,
        .name = {'a','h','x'},
        .official = false,
        .length = 2,
        .mode = OP_MODE_POST_INDIRECT_Y
    },
    [OP_94_STY] = {
        .op = 0x94,
        .name = {'s','t','y'},
        .official = true,
        .length = 2,
        .mode = OP_MODE_ZERO_PAGE_X
    },
    [OP_95_STA] = {
        .op = 0x95,
        .name = {'s','t','a'},
        .official = true,
        .length = 2,
        .mode = OP_MODE_ZERO_PAGE_X
    },
    [OP_96_STX] = {
        .op = 0x96,
        .name = {'s','t','x'},
        .official = true,
        .length = 2,
        .mode = OP_MODE_ZERO_PAGE_Y
    },
    [OP_97_SAX_UNOFFICIAL] = {
        .op = 0x97,
        .name = {'s','a','x'},
        .official = false,
        .length = 2,
        .mode = OP_MODE_ZERO_PAGE_Y
    },
    [OP_98_TYA] = {
        .op = 0x98,
        .name = {'t','y','a'},
        .official = true,
        .length = 1,
        .mode = OP_MODE_IMPLIED
    },
    [OP_99_STA] = {
        .op = 0x99,
        .name = {'s','t','a'},
        .official = true,
        .length = 3,
        .mode = OP_MODE_ABSOLUTE_Y
    },
    [OP_9A_TXS] = {
        .op = 0x9A,
        .name = {'t','x','s'},
        .official = true,
        .length = 1,
        .mode = OP_MODE_IMPLIED
    },
    [OP_9B_TAS_UNOFFICIAL] = {
        .op = 0x9B,
        .name = {'t','a','s'},
        .official = false,
        .length = 3,
        .mode = OP_MODE_ABSOLUTE_Y
    },
    [OP_9C_SHY_UNOFFICIAL] = {
        .op = 0x9C,
        .name = {'s','h','y'},
        .official = false,
        .length = 3,
        .mode = OP_MODE_ABSOLUTE_X
    },
    [OP_9D_STA] = {
        .op = 0x9D,
        .name = {'s','t','a'},
        .official = true,
        .length = 3,
        .mode = OP_MODE_ABSOLUTE_X
    },
    [OP_9E_SHX_UNOFFICIAL] = {
        .op = 0x9E,
        .name = {'s','h','x'},
        .official = false,
        .length = 3,
        .mode = OP_MODE_ABSOLUTE_Y
    },
    [OP_9F_AHX_UNOFFICIAL] = {
        .op = 0x9F,
        .name = {'a','h','x'},
        .official = false,
        .length = 3,
        .mode = OP_MODE_ABSOLUTE_Y
    },
    [OP_A0_LDY] = {
        .op = 0xA0,
        .name = {'l','d','y'},
        .official = true,
        .length = 2,
        .mode = OP_MODE_IMMEDIATE
    },
    [OP_A1_LDA] = {
        .op = 0xA1,
        .name = {'l','d','a'},
        .official = true,
        .length = 2,
        .mode = OP_MODE_PRE_INDIRECT_X
    },
    [OP_A2_LDX] = {
        .op = 0xA2,
        .name = {'l','d','x'},
        .official = true,
        .length = 2,
        .mode = OP_MODE_IMMEDIATE
    },
    [OP_A3_LAX_UNOFFICIAL] = {
        .op = 0xA3,
        .name = {'l','a','x'},
        .official = false,
        .length = 2,
        .mode = OP_MODE_PRE_INDIRECT_X
    },
    [OP_A4_LDY] = {
        .op = 0xA4,
        .name = {'l','d','y'},
        .official = true,
        .length = 2,
        .mode = OP_MODE_ZERO_PAGE
    },
    [OP_A5_LDA] = {
        .op = 0xA5,
        .name = {'l','d','a'},
        .official = true,
        .length = 2,
        .mode = OP_MODE_ZERO_PAGE
    },
    [OP_A6_LDX] = {
        .op = 0xA6,
        .name = {'l','d','x'},
        .official = true,
        .length = 2,
        .mode = OP_MODE_ZERO_PAGE
    },
    [OP_A7_LAX_UNOFFICIAL] = {
        .op = 0xA7,
        .name = {'l','a','x'},
        .official = false,
        .length = 2,
        .mode = OP_MODE_ZERO_PAGE
    },
    [OP_A8_TAY] = {
        .op = 0xA8,
        .name = {'t','a','y'},
        .official = true,
        .length = 1,
        .mode = OP_MODE_IMPLIED
    },
    [OP_A9_LDA] = {
        .op = 0xA9,
        .name = {'l','d','a'},
        .official = true,
        .length = 2,
        .mode = OP_MODE_IMMEDIATE
    },
    [OP_AA_TAX] = {
        .op = 0xAA,
        .name = {'t','a','x'},
        .official = true,
        .length = 1,
        .mode = OP_MODE_IMPLIED
    },
    [OP_AB_LAX_UNOFFICIAL] = {
        .op = 0xAB,
        .name = {'l','a','x'},
        .official = false,
        .length = 2,
        .mode = OP_MODE_IMMEDIATE
    },
    [OP_AC_LDY] = {
        .op = 0xAC,
        .name = {'l','d','y'},
        .official = true,
        .length = 3,
        .mode = OP_MODE_ABSOLUTE
    },
    [OP_AD_LDA] = {
        .op = 0xAD,
        .name = {'l','d','a'},
        .official = true,
        .length = 3,
        .mode = OP_MODE_ABSOLUTE
    },
    [OP_AE_LDX] = {
        .op = 0xAE,
        .name = {'l','d','x'},
        .official = true,
        .length = 3,
        .mode = OP_MODE_ABSOLUTE
    },
    [OP_AF_LAX_UNOFFICIAL] = {
        .op = 0xAF,
        .name = {'l','a','x'},
        .official = false,
        .length = 3,
        .mode = OP_MODE_ABSOLUTE
    },
    [OP_B0_BCS] = {
        .op = 0xB0,
        .name = {'b','c','s'},
        .official = true,
        .length = 2,
        .mode = OP_MODE_RELATIVE
    },
    [OP_B1_LDA] = {
        .op = 0xB1,
        .name = {'l','d','a'},
        .official = true,
        .length = 2,
        .mode = OP_MODE_POST_INDIRECT_Y
    },
    [OP_B2_STP_UNOFFICIAL] = {
        .op = 0xB2,
        .name = {'s','t','p'},
        .official = false,
        .length = 1,
        .mode = OP_MODE_IMPLIED
    },
    [OP_B3_LAX_UNOFFICIAL] = {
        .op = 0xB3,
        .name = {'l','a','x'},
        .official = false,
        .length = 2,
        .mode = OP_MODE_POST_INDIRECT_Y
    },
    [OP_B4_LDY] = {
        .op = 0xB4,
        .name = {'l','d','y'},
        .official = true,
        .length = 2,
        .mode = OP_MODE_ZERO_PAGE_X
    },
    [OP_B5_LDA] = {
        .op = 0xB5,
        .name = {'l','d','a'},
        .official = true,
        .length = 2,
        .mode = OP_MODE_ZERO_PAGE_X
    },
    [OP_B6_LDX] = {
        .op = 0xB6,
        .name = {'l','d','x'},
        .official = true,
        .length = 2,
        .mode = OP_MODE_ZERO_PAGE_Y
    },
    [OP_B7_LAX_UNOFFICIAL] = {
        .op = 0xB7,
        .name = {'l','a','x'},
        .official = false,
        .length = 2,
        .mode = OP_MODE_ZERO_PAGE_Y
    },
    [OP_B8_CLV] = {
        .op = 0xB8,
        .name = {'c','l','v'},
        .official = true,
        .length = 1,
        .mode = OP_MODE_IMPLIED
    },
    [OP_B9_LDA] = {
        .op = 0xB9,
        .name = {'l','d','a'},
        .official = true,
        .length = 3,
        .mode = OP_MODE_ABSOLUTE_Y
    },
    [OP_BA_TSX] = {
        .op = 0xBA,
        .name = {'t','s','x'},
        .official = true,
        .length = 1,
        .mode = OP_MODE_IMPLIED
    },
    [OP_BB_LAS_UNOFFICIAL] = {
        .op = 0xBB,
        .name = {'l','a','s'},
        .official = false,
        .length = 3,
        .mode = OP_MODE_ABSOLUTE_Y
    },
    [OP_BC_LDY] = {
        .op = 0xBC,
        .name = {'l','d','y'},
        .official = true,
        .length = 3,
        .mode = OP_MODE_ABSOLUTE_X
    },
    [OP_BD_LDA] = {
        .op = 0xBD,
        .name = {'l','d','a'},
        .official = true,
        .length = 3,
        .mode = OP_MODE_ABSOLUTE_X
    },
    [OP_BE_LDX] = {
        .op = 0xBE,
        .name = {'l','d','x'},
        .official = true,
        .length = 3,
        .mode = OP_MODE_ABSOLUTE_Y
    },
    [OP_BF_LAX_UNOFFICIAL] = {
        .op = 0xBF,
        .name = {'l','a','x'},
        .official = false,
        .length = 3,
        .mode = OP_MODE_ABSOLUTE_Y
    },
    [OP_C0_CPY] = {
        .op = 0xC0,
        .name = {'c','p','y'},
        .official = true,
        .length = 2,
        .mode = OP_MODE_IMMEDIATE
    },
    [OP_C1_CMP] = {
        .op = 0xC1,
        .name = {'c','m','p'},
        .official = true,
        .length = 2,
        .mode = OP_MODE_PRE_INDIRECT_X
    },
    [OP_C2_NOP_UNOFFICIAL] = {
        .op = 0xC2,
        .name = {'n','o','p'},
        .official = false,
        .length = 2,
        .mode = OP_MODE_IMMEDIATE
    },
    [OP_C3_DCP_UNOFFICIAL] = {
        .op = 0xC3,
        .name = {'d','c','p'},
        .official = false,
        .length = 2,
        .mode = OP_MODE_PRE_INDIRECT_X
    },
    [OP_C4_CPY] = {
        .op = 0xC4,
        .name = {'c','p','y'},
        .official = true,
        .length = 2,
        .mode = OP_MODE_ZERO_PAGE
    },
    [OP_C5_CMP] = {
        .op = 0xC5,
        .name = {'c','m','p'},
        .official = true,
        .length = 2,
        .mode = OP_MODE_ZERO_PAGE
    },
    [OP_C6_DEC] = {
        .op = 0xC6,
        .name = {'d','e','c'},
        .official = true,
        .length = 2,
        .mode = OP_MODE_ZERO_PAGE
    },
    [OP_C7_DCP_UNOFFICIAL] = {
        .op = 0xC7,
        .name = {'d','c','p'},
        .official = false,
        .length = 2,
        .mode = OP_MODE_ZERO_PAGE
    },
    [OP_C8_INY] = {
        .op = 0xC8,
        .name = {'i','n','y'},
        .official = true,
        .length = 1,
        .mode = OP_MODE_IMPLIED
    },
    [OP_C9_CMP] = {
        .op = 0xC9,
        .name = {'c','m','p'},
        .official = true,
        .length = 2,
        .mode = OP_MODE_IMMEDIATE
    },
    [OP_CA_DEX] = {
        .op = 0xCA,
        .name = {'d','e','x'},
        .official = true,
        .length = 1,
        .mode = OP_MODE_IMPLIED
    },
    [OP_CB_AXS_UNOFFICIAL] = {
        .op = 0xCB,
        .name = {'a','x','s'},
        .official = false,
        .length = 2,
        .mode = OP_MODE_IMMEDIATE
    },
    [OP_CC_CPY] = {
        .op = 0xCC,
        .name = {'c','p','y'},
        .official = true,
        .length = 3,
        .mode = OP_MODE_ABSOLUTE
    },
    [OP_CD_CMP] = {
        .op = 0xCD,
        .name = {'c','m','p'},
        .official = true,
        .length = 3,
        .mode = OP_MODE_ABSOLUTE
    },
    [OP_CE_DEC] = {
        .op = 0xCE,
        .name = {'d','e','c'},
        .official = true,
        .length = 3,
        .mode = OP_MODE_ABSOLUTE
    },
    [OP_CF_DCP_UNOFFICIAL] = {
        .op = 0xCF,
        .name = {'d','c','p'},
        .official = false,
        .length = 3,
        .mode = OP_MODE_ABSOLUTE
    },
    [OP_D0_BNE] = {
        .op = 0xD0,
        .name = {'b','n','e'},
        .official = true,
        .length = 2,
        .mode = OP_MODE_RELATIVE
    },
    [OP_D1_CMP] = {
        .op = 0xD1,
        .name = {'c','m','p'},
        .official = true,
        .length = 2,
        .mode = OP_MODE_POST_INDIRECT_Y
    },
    [OP_D2_STP_UNOFFICIAL] = {
        .op = 0xD2,
        .name = {'s','t','p'},
        .official = false,
        .length = 1,
        .mode = OP_MODE_IMPLIED
    },
    [OP_D3_DCP_UNOFFICIAL] = {
        .op = 0xD3,
        .name = {'d','c','p'},
        .official = false,
        .length = 2,
        .mode = OP_MODE_POST_INDIRECT_Y
    },
    [OP_D4_NOP_UNOFFICIAL] = {
        .op = 0xD4,
        .name = {'n','o','p'},
        .official = false,
        .length = 2,
        .mode = OP_MODE_ZERO_PAGE_X
    },
    [OP_D5_CMP] = {
        .op = 0xD5,
        .name = {'c','m','p'},
        .official = true,
        .length = 2,
        .mode = OP_MODE_ZERO_PAGE_X
    },
    [OP_D6_DEC] = {
        .op = 0xD6,
        .name = {'d','e','c'},
        .official = true,
        .length = 2,
        .mode = OP_MODE_ZERO_PAGE_X
    },
    [OP_D7_DCP_UNOFFICIAL] = {
        .op = 0xD7,
        .name = {'d','c','p'},
        .official = false,
        .length = 2,
        .mode = OP_MODE_ZERO_PAGE_X
    },
    [OP_D8_CLD] = {
        .op = 0xD8,
        .name = {'c','l','d'},
        .official = true,
        .length = 1,
        .mode = OP_MODE_IMPLIED
    },
    [OP_D9_CMP] = {
        .op = 0xD9,
        .name = {'c','m','p'},
        .official = true,
        .length = 3,
        .mode = OP_MODE_ABSOLUTE_Y
    },
    [OP_DA_NOP_UNOFFICIAL] = {
        .op = 0xDA,
        .name = {'n','o','p'},
        .official = false,
        .length = 1,
        .mode = OP_MODE_IMPLIED
    },
    [OP_DB_DCP_UNOFFICIAL] = {
        .op = 0xDB,
        .name = {'d','c','p'},
        .official = false,
        .length = 3,
        .mode = OP_MODE_ABSOLUTE_Y
    },
    [OP_DC_NOP_UNOFFICIAL] = {
        .op = 0xDC,
        .name = {'n','o','p'},
        .official = false,
        .length = 3,
        .mode = OP_MODE_ABSOLUTE_X
    },
    [OP_DD_CMP] = {
        .op = 0xDD,
        .name = {'c','m','p'},
        .official = true,
        .length = 3,
        .mode = OP_MODE_ABSOLUTE_X
    },
    [OP_DE_DEC] = {
        .op = 0xDE,
        .name = {'d','e','c'},
        .official = true,
        .length = 3,
        .mode = OP_MODE_ABSOLUTE_X
    },
    [OP_DF_DCP_UNOFFICIAL] = {
        .op = 0xDF,
        .name = {'d','c','p'},
        .official = false,
        .length = 3,
        .mode = OP_MODE_ABSOLUTE_X
    },
    [OP_E0_CPX] = {
        .op = 0xE0,
        .name = {'c','p','x'},
        .official = true,
        .length = 2,
        .mode = OP_MODE_IMMEDIATE
    },
    [OP_E1_SBC] = {
        .op = 0xE1,
        .name = {'s','b','c'},
        .official = true,
        .length = 2,
        .mode = OP_MODE_PRE_INDIRECT_X
    },
    [OP_E2_NOP_UNOFFICIAL] = {
        .op = 0xE2,
        .name = {'n','o','p'},
        .official = false,
        .length = 2,
        .mode = OP_MODE_IMMEDIATE
    },
    [OP_E3_ISC_UNOFFICIAL] = {
        .op = 0xE3,
        .name = {'i','s','c'},
        .official = false,
        .length = 2,
        .mode = OP_MODE_PRE_INDIRECT_X
    },
    [OP_E4_CPX] = {
        .op = 0xE4,
        .name = {'c','p','x'},
        .official = true,
        .length = 2,
        .mode = OP_MODE_ZERO_PAGE
    },
    [OP_E5_SBC] = {
        .op = 0xE5,
        .name = {'s','b','c'},
        .official = true,
        .length = 2,
        .mode = OP_MODE_ZERO_PAGE
    },
    [OP_E6_INC] = {
        .op = 0xE6,
        .name = {'i','n','c'},
        .official = true,
        .length = 2,
        .mode = OP_MODE_ZERO_PAGE
    },
    [OP_E7_ISC_UNOFFICIAL] = {
        .op = 0xE7,
        .name = {'i','s','c'},
        .official = false,
        .length = 2,
        .mode = OP_MODE_ZERO_PAGE
    },
    [OP_E8_INX] = {
        .op = 0xE8,
        .name = {'i','n','x'},
        .official = true,
        .length = 1,
        .mode = OP_MODE_IMPLIED
    },
    [OP_E9_SBC] = {
        .op = 0xE9,
        .name = {'s','b','c'},
        .official = true,
        .length = 2,
        .mode = OP_MODE_IMMEDIATE
    },
    [OP_EA_NOP] = {
        .op = 0xEA,
        .name = {'n','o','p'},
        .official = true,
        .length = 1,
        .mode = OP_MODE_IMPLIED
    },
    [OP_EB_SBC_UNOFFICIAL] = {
        .op = 0xEB,
        .name = {'s','b','c'},
        .official = false,
        .length = 2,
        .mode = OP_MODE_IMMEDIATE
    },
    [OP_EC_CPX] = {
        .op = 0xEC,
        .name = {'c','p','x'},
        .official = true,
        .length = 3,
        .mode = OP_MODE_ABSOLUTE
    },
    [OP_ED_SBC] = {
        .op = 0xED,
        .name = {'s','b','c'},
        .official = true,
        .length = 3,
        .mode = OP_MODE_ABSOLUTE
    },
    [OP_EE_INC] = {
        .op = 0xEE,
        .name = {'i','n','c'},
        .official = true,
        .length = 3,
        .mode = OP_MODE_ABSOLUTE
    },
    [OP_EF_ISC_UNOFFICIAL] = {
        .op = 0xEF,
        .name = {'i','s','c'},
        .official = false,
        .length = 3,
        .mode = OP_MODE_ABSOLUTE
    },
    [OP_F0_BEQ] = {
        .op = 0xF0,
        .name = {'b','e','q'},
        .official = true,
        .length = 2,
        .mode = OP_MODE_RELATIVE
    },
    [OP_F1_SBC] = {
        .op = 0xF1,
        .name = {'s','b','c'},
        .official = true,
        .length = 2,
        .mode = OP_MODE_POST_INDIRECT_Y
    },
    [OP_F2_STP_UNOFFICIAL] = {
        .op = 0xF2,
        .name = {'s','t','p'},
        .official = false,
        .length = 1,
        .mode = OP_MODE_IMPLIED
    },
    [OP_F3_ISC_UNOFFICIAL] = {
        .op = 0xF3,
        .name = {'i','s','c'},
        .official = false,
        .length = 2,
        .mode = OP_MODE_POST_INDIRECT_Y
    },
    [OP_F4_NOP_UNOFFICIAL] = {
        .op = 0xF4,
        .name = {'n','o','p'},
        .official = false,
        .length = 2,
        .mode = OP_MODE_ZERO_PAGE_X
    },
    [OP_F5_SBC] = {
        .op = 0xF5,
        .name = {'s','b','c'},
        .official = true,
        .length = 2,
        .mode = OP_MODE_ZERO_PAGE_X
    },
    [OP_F6_INC] = {
        .op = 0xF6,
        .name = {'i','n','c'},
        .official = true,
        .length = 2,
        .mode = OP_MODE_ZERO_PAGE_X
    },
    [OP_F7_ISC_UNOFFICIAL] = {
        .op = 0xF7,
        .name = {'i','s','c'},
        .official = false,
        .length = 2,
        .mode = OP_MODE_ZERO_PAGE_X
    },
    [OP_F8_SED] = {
        .op = 0xF8,
        .name = {'s','e','d'},
        .official = true,
        .length = 1,
        .mode = OP_MODE_IMPLIED
    },
    [OP_F9_SBC] = {
        .op = 0xF9,
        .name = {'s','b','c'},
        .official = true,
        .length = 3,
        .mode = OP_MODE_ABSOLUTE_Y
    },
    [OP_FA_NOP_UNOFFICIAL] = {
        .op = 0xFA,
        .name = {'n','o','p'},
        .official = false,
        .length = 1,
        .mode = OP_MODE_IMPLIED
    },
    [OP_FB_ISC_UNOFFICIAL] = {
        .op = 0xFB,
        .name = {'i','s','c'},
        .official = false,
        .length = 3,
        .mode = OP_MODE_ABSOLUTE_Y
    },
    [OP_FC_NOP_UNOFFICIAL] = {
        .op = 0xFC,
        .name = {'n','o','p'},
        .official = false,
        .length = 3,
        .mode = OP_MODE_ABSOLUTE_X
    },
    [OP_FD_SBC] = {
        .op = 0xFD,
        .name = {'s','b','c'},
        .official = true,
        .length = 3,
        .mode = OP_MODE_ABSOLUTE_X
    },
    [OP_FE_INC] = {
        .op = 0xFE,
        .name = {'i','n','c'},
        .official = true,
        .length = 3,
        .mode = OP_MODE_ABSOLUTE_X
    },
    [OP_FF_ISC_UNOFFICIAL] = {
        .op = 0xFF,
        .name = {'i','s','c'},
        .official = false,
        .length = 3,
        .mode = OP_MODE_ABSOLUTE_X
    },
};
