// *** WARNING ***
// This file is generated by gendriver.rb
// Keep untouched or ruin the abstraction
#pragma once
#include "utils.h"
#include "drivers.h"
#include "core.h"

// generated event detacher
void disas_driver_detach_cpu_decode(disas_driver_ref self, core_ref core);
void disas_driver_detach_cpu_read(disas_driver_ref self, core_ref core);
void disas_driver_detach_core_start(disas_driver_ref self, core_ref core);
void disas_driver_detach_core_quit(disas_driver_ref self, core_ref core);

// required implementations
void disas_driver_destroy(disas_driver_ref self);
disas_driver_ref disas_driver_create(core_ref core, const char * out_path);
void disas_driver_on_cpu_decode(disas_driver_ref self, cpu_ref cpu, uint16_t pc);
void disas_driver_on_cpu_read(disas_driver_ref self, cpu_ref cpu, uint16_t addr, size_t size);
void disas_driver_on_core_start(disas_driver_ref self, core_ref core);
void disas_driver_on_core_quit(disas_driver_ref self, core_ref core);
