// *** WARNING ***
// This file is generated by genevents.rb
// Keep untouched or ruin the abstraction
#pragma once
#include "utils.h"
#include "event_id.h"
#include "core_event_emitter.h"
#include "bus_event_emitter.h"
#include "ppu_event_emitter.h"
#include "cpu_event_emitter.h"
#include "apu_event_emitter.h"
#include "input_event_emitter.h"
#include "logger_event_emitter.h"

typedef struct events *events_ref;

typedef struct events {
    core_event_emitter_t core;
    bus_event_emitter_t bus;
    ppu_event_emitter_t ppu;
    cpu_event_emitter_t cpu;
    apu_event_emitter_t apu;
    input_event_emitter_t input;
    logger_event_emitter_t logger;
} events_t;

static inline void events_detach_all(events_ref self)
{
    core_event_detach_all(&self->core);
    bus_event_detach_all(&self->bus);
    ppu_event_detach_all(&self->ppu);
    cpu_event_detach_all(&self->cpu);
    apu_event_detach_all(&self->apu);
    input_event_detach_all(&self->input);
    logger_event_detach_all(&self->logger);
}
