// *** WARNING ***
// This file is generated by genevents.rb
// Keep untouched or ruin the abstraction
#pragma once
#include "utils.h"

typedef void (*logger_event_callback_on_event_trace_t)(void *context, int domain_id, int event_id);

typedef struct logger_event_listener {
    void *context;
    // event trace
    logger_event_callback_on_event_trace_t on_event_trace;
} logger_event_listener_t;
