// *** WARNING ***
// This file is generated by gendriver.rb
// Keep untouched or ruin the abstraction
#pragma once
#include "utils.h"
#include "drivers.h"
#include "core.h"
#include "args.h"

// generated event detacher
void sdl_driver_detach_ppu_frame(sdl_driver_ref self, core_ref core);
void sdl_driver_detach_ppu_scanline(sdl_driver_ref self, core_ref core);
void sdl_driver_detach_core_start(sdl_driver_ref self, core_ref core);
void sdl_driver_detach_core_poll_in_pause(sdl_driver_ref self, core_ref core);
void sdl_driver_detach_core_pause(sdl_driver_ref self, core_ref core);
void sdl_driver_detach_core_resume(sdl_driver_ref self, core_ref core);
void sdl_driver_detach_apu_level30(sdl_driver_ref self, core_ref core);

// required implementations
void sdl_driver_destroy(sdl_driver_ref self);
sdl_driver_ref sdl_driver_create(core_ref core, args_t * args);
void sdl_driver_on_ppu_frame(sdl_driver_ref self, ppu_ref ppu, uint64_t frames);
void sdl_driver_on_ppu_scanline(sdl_driver_ref self, ppu_ref ppu, int line, const uint16_t * dots);
void sdl_driver_on_core_start(sdl_driver_ref self, core_ref core);
void sdl_driver_on_core_poll_in_pause(sdl_driver_ref self, core_ref core);
void sdl_driver_on_core_pause(sdl_driver_ref self, core_ref core);
void sdl_driver_on_core_resume(sdl_driver_ref self, core_ref core);
void sdl_driver_on_apu_level30(sdl_driver_ref self, apu_ref apu, float level);
