// *** WARNING ***
// This file is generated by gendriver.rb
// Keep untouched or ruin the abstraction
#include "drivers.h"
#include "tracer_driver_impl.h"

tracer_driver_ref tracer_driver_plug(core_ref core, const args_t * args)
{
    tracer_driver_ref driver = NULL;

    GUARD(driver = tracer_driver_create(core, args));

    cpu_event_attach_listener(&core->events.cpu,
        &(cpu_event_listener_t) {
            .context = driver,
                    .on_step = (cpu_event_callback_on_step_t)tracer_driver_on_cpu_step,
        });
    apu_event_attach_listener(&core->events.apu,
        &(apu_event_listener_t) {
            .context = driver,
                    .on_sample = (apu_event_callback_on_sample_t)tracer_driver_on_apu_sample,
        });
    ppu_event_attach_listener(&core->events.ppu,
        &(ppu_event_listener_t) {
            .context = driver,
                    .on_scanline = (ppu_event_callback_on_scanline_t)tracer_driver_on_ppu_scanline,
        });
    core_event_attach_listener(&core->events.core,
        &(core_event_listener_t) {
            .context = driver,
                    .on_pause = (core_event_callback_on_pause_t)tracer_driver_on_core_pause,
                .on_quit = (core_event_callback_on_quit_t)tracer_driver_on_core_quit,
                .on_start = (core_event_callback_on_start_t)tracer_driver_on_core_start,
        });

    core_event_attach_listener(&core->events.core, &(core_event_listener_t) {
        .context = driver,
        .on_destroy = (core_event_callback_on_destroy_t)tracer_driver_destroy,
    });

    return driver;
error:
    tracer_driver_destroy(driver);
    return NULL;
}

void tracer_driver_detach_cpu_step(tracer_driver_ref self, core_ref core)
{
    cpu_event_emitter_t *emitter = &core->events.cpu;
    cpu_event_detach_listener_on_step(emitter, self);
}
void tracer_driver_detach_apu_sample(tracer_driver_ref self, core_ref core)
{
    apu_event_emitter_t *emitter = &core->events.apu;
    apu_event_detach_listener_on_sample(emitter, self);
}
void tracer_driver_detach_ppu_scanline(tracer_driver_ref self, core_ref core)
{
    ppu_event_emitter_t *emitter = &core->events.ppu;
    ppu_event_detach_listener_on_scanline(emitter, self);
}
void tracer_driver_detach_core_pause(tracer_driver_ref self, core_ref core)
{
    core_event_emitter_t *emitter = &core->events.core;
    core_event_detach_listener_on_pause(emitter, self);
}
void tracer_driver_detach_core_quit(tracer_driver_ref self, core_ref core)
{
    core_event_emitter_t *emitter = &core->events.core;
    core_event_detach_listener_on_quit(emitter, self);
}
void tracer_driver_detach_core_start(tracer_driver_ref self, core_ref core)
{
    core_event_emitter_t *emitter = &core->events.core;
    core_event_detach_listener_on_start(emitter, self);
}

void tracer_driver_unplug(core_ref core, tracer_driver_ref driver)
{
    tracer_driver_detach_cpu_step(driver, core);
    tracer_driver_detach_apu_sample(driver, core);
    tracer_driver_detach_ppu_scanline(driver, core);
    tracer_driver_detach_core_pause(driver, core);
    tracer_driver_detach_core_quit(driver, core);
    tracer_driver_detach_core_start(driver, core);
    core_event_detach_listener_on_destroy(&core->events.core, driver);

    tracer_driver_destroy(driver);
}
