// *** WARNING ***
// This file is generated by gendriver.rb
// Keep untouched or ruin the abstraction
#pragma once
#include "utils.h"
#include "drivers.h"
#include "core.h"
#include "args.h"

// generated event detacher
void tracer_driver_detach_cpu_step(tracer_driver_ref self, core_ref core);
void tracer_driver_detach_apu_sample(tracer_driver_ref self, core_ref core);
void tracer_driver_detach_ppu_scanline(tracer_driver_ref self, core_ref core);
void tracer_driver_detach_core_pause(tracer_driver_ref self, core_ref core);
void tracer_driver_detach_core_quit(tracer_driver_ref self, core_ref core);
void tracer_driver_detach_core_start(tracer_driver_ref self, core_ref core);

// required implementations
void tracer_driver_destroy(tracer_driver_ref self);
tracer_driver_ref tracer_driver_create(core_ref core, const args_t * args);
void tracer_driver_on_cpu_step(tracer_driver_ref self, cpu_ref cpu);
void tracer_driver_on_apu_sample(tracer_driver_ref self, apu_ref apu, uint8_t pulse, uint8_t tnd);
void tracer_driver_on_ppu_scanline(tracer_driver_ref self, ppu_ref ppu, int line, const uint16_t * dots);
void tracer_driver_on_core_pause(tracer_driver_ref self, core_ref core);
void tracer_driver_on_core_quit(tracer_driver_ref self, core_ref core);
void tracer_driver_on_core_start(tracer_driver_ref self, core_ref core);
